# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 05:55
from __future__ import unicode_literals

import certificate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('certificate_id', models.CharField(max_length=15)),
                ('vpoker_stuid', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to=certificate.models.directory_path)),
            ],
        ),
    ]
