# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_data',
            name='certificate_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate_data',
            name='vpoker_stuid',
            field=models.CharField(max_length=20),
        ),
    ]
